### ISSUE TITLE
直接安装了你的版本，没有类型选项，如图

### ISSUE THREAD

**Issue by wendaleruan** [shadowxiehao/external-media-without-import-1.1.3#1]
<img width="1087" alt="bug" src="https://user-images.githubusercontent.com/7631911/97778406-e7f9c800-1bb1-11eb-9b07-e61216535b82.png">
 wp版本是最新的5.5.3

**Comment by vifimx** [comment]
emmm 需要输入一个无效的地址就可以弹出来了,比如输入"123"
